apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: nmx2seqih-java-springboot
  janus-idp.io/tekton: nmx2seqih-java-springboot
  backstage.io/kubernetes-id: nmx2seqih-java-springboot
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: nmx2seqih-java-springboot
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
